# Generated by Django 4.2.16 on 2026-03-15 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0004_auto_20260315_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='activity_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checkin_date',
            field=models.DateField(verbose_name='Check-in date'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='energy_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='mood_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
